"""Deterministic GitHub-baseline vs AOS contrast artifacts.

Reads only committed, replayable evidence — the governance benchmark
cases and the committed example records — and emits
``benchmarks/contrast/contrast.json`` plus a Markdown rendering of it.
The output is a pure function of the committed files: regenerating must
produce identical bytes, which the test suite asserts on every CI run,
so the public contrast can never drift from the evidence it summarizes.

The GitHub baseline in every row is operator-declared from historical
platform state (scope: required status checks, not full
merge-readiness). Expected verdicts exist only as test assertions —
nothing here feeds the evaluator.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "benchmarks" / "contrast"

# committed example evidence with operator-declared baselines; benchmark
# cases carry their own baseline in case.json
_EXAMPLE_ROWS = (
    {
        "case": "examples/pr-evidence-record.json",
        "baseline": {
            "github_merge_ready": True,
            "declared_by": "operator",
            "note": "all signals green on the head commit",
        },
        "gap_kind": "none (control case)",
    },
    {
        "case": "examples/zero-required-record.json",
        "baseline": {
            "github_merge_ready": True,
            "declared_by": "operator",
            "note": "required status check green; self-test jobs failed "
            "but were not required",
        },
        "gap_kind": "decision gap (zero required at the gate)",
    },
    {
        "case": "examples/green-but-incomplete-record.json",
        "baseline": {
            "github_merge_ready": True,
            "declared_by": "operator",
            "note": "dashboard fully green; one control never ran",
        },
        "gap_kind": "advisory-visibility gap",
    },
)


def _record_verdict(path: Path) -> dict[str, Any]:
    record = json.loads(path.read_text(encoding="utf-8"))
    return {
        "verdict": record["verdict"],
        "can_block": record["can_block"],
        "record_digest": record["record_digest"],
        "reason_rules": sorted(
            {reason["rule"] for reason in record.get("reasons", [])}
        ),
    }


def build_contrast() -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    for case_dir in sorted((ROOT / "benchmarks" / "cases").iterdir()):
        case = json.loads(
            (case_dir / "case.json").read_text(encoding="utf-8")
        )
        rows.append(
            {
                "case": f"benchmarks/cases/{case_dir.name}",
                "baseline": case["baseline"],
                "classification": case["classification"],
                "aos": _record_verdict(case_dir / "gate-decision.json"),
            }
        )
    for spec in _EXAMPLE_ROWS:
        case_path = str(spec["case"])
        rows.append(
            {
                "case": case_path,
                "baseline": spec["baseline"],
                "classification": spec["gap_kind"],
                "aos": _record_verdict(ROOT / case_path),
            }
        )
    return {
        "schema_version": "contrast-v0",
        "boundary": (
            "baselines are operator-declared from historical platform "
            "state; scope is required status checks, not full "
            "merge-readiness; no security or quality claim is made"
        ),
        "rows": rows,
    }


def render_markdown(contrast: dict[str, Any]) -> str:
    lines = [
        "# GitHub baseline vs AOS verdict — committed contrast",
        "",
        "Generated by `tools/contrast.py` from committed, replayable",
        "evidence only; the test suite regenerates it on every CI run and",
        "asserts byte equality, so this table cannot drift from the",
        "evidence. Baselines are operator-declared; scope is required",
        "status checks, not full merge-readiness.",
        "",
        "| Case | GitHub baseline | AOS verdict | Gap |",
        "| --- | --- | --- | --- |",
    ]
    for row in contrast["rows"]:
        ready = (
            "merge-ready"
            if row["baseline"].get("github_merge_ready")
            else "not merge-ready"
        )
        lines.append(
            f"| `{row['case']}` | {ready} (operator-declared) | "
            f"**{row['aos']['verdict']}** | {row['classification']} |"
        )
    lines += [
        "",
        "Every row replays offline from the committed files; decision",
        "records carry UNSIGNED_NOT_OFFICIAL status.",
        "",
        "## Separate adversarial regression coverage",
        "",
        "The contrast rows above are evidence-backed baseline rows.",
        "Synthetic adversarial fixtures are intentionally excluded from",
        "the contrast claim. Their positive, negative, and neutral",
        "coverage is listed in",
        "[the adversarial matrix](../adversarial/MATRIX.md).",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    contrast = build_contrast()
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "contrast.json").write_text(
        json.dumps(contrast, indent=2, ensure_ascii=False, sort_keys=True)
        + "\n",
        encoding="utf-8",
        newline="\n",
    )
    (OUT_DIR / "CONTRAST.md").write_text(
        render_markdown(contrast), encoding="utf-8", newline="\n"
    )
    print(f"contrast rows: {len(contrast['rows'])}")


if __name__ == "__main__":
    main()
